languageCode = "en-us"
title = " Automating CI/CD on AWS with GitHub Actions"
theme = "hugo-theme-learn"
uglyurls=true
RelativeURLs=true

[params]
themeVariant = "mine"
showVisitedLinks = true
author = "Jenna Pederson, Kris Howard"
description = "Automating CI/CD on AWS with GitHub Actions"
disableSearch = true
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @jennapederson"
identifier = "tw1"
url = "https://twitter.comjennapederson"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> /in/jennapederson"
identifier = "li1"
url = "https://www.linkedin.com/in/jennapederson/"
weight = 2

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @web_goddess"
identifier = "tw2"
url = "https://twitter.com/web_goddess"
weight = 3

[[menu.shortcuts]]
name = "<i class='fab fa-linkedin fa-lg'></i> /in/kristinehoward"
identifier = "li2"
url = "https://www.linkedin.com/in/kristinehoward/"
weight = 4